// <auto-generated />
using System;
using DA09_QLSK.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DA09_QLSK.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DA09_QLSK.Models.Account", b =>
                {
                    b.Property<string>("Account_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("account_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Account_id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("DA09_QLSK.Models.DangKy", b =>
                {
                    b.Property<int>("MaDK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MaSK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("attended_at")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_attended")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("registration_date")
                        .HasColumnType("datetime2");

                    b.HasKey("MaDK");

                    b.ToTable("DangKy");
                });

            modelBuilder.Entity("DA09_QLSK.Models.Khoa", b =>
                {
                    b.Property<string>("MaKhoa")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenKhoa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKhoa");

                    b.ToTable("Khoa");
                });

            modelBuilder.Entity("DA09_QLSK.Models.Khoa_SuKien", b =>
                {
                    b.Property<string>("MaKhoa")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaSK")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaKhoa", "MaSK");

                    b.ToTable("Khoa_SuKien");
                });

            modelBuilder.Entity("DA09_QLSK.Models.Notification", b =>
                {
                    b.Property<int>("notification_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MaSK")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("sent_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("notification_id");

                    b.HasIndex("MaSK");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("DA09_QLSK.Models.PhanCong", b =>
                {
                    b.Property<int>("MaPC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Account_id")
                        .HasColumnName("account_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaSK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NhiemVu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ThoiGianPhanCong")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThaiPC")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPC");

                    b.HasIndex("Account_id");

                    b.ToTable("PhanCong");
                });

            modelBuilder.Entity("DA09_QLSK.Models.PhanLoaiSK", b =>
                {
                    b.Property<string>("MaLoaiSK")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MoTaLoaiSK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLoai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLoaiSK");

                    b.ToTable("PhanLoaiSK");
                });

            modelBuilder.Entity("DA09_QLSK.Models.SinhVien", b =>
                {
                    b.Property<string>("MaSV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Account_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaKhoa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSV")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSV");

                    b.ToTable("SinhVien");
                });

            modelBuilder.Entity("DA09_QLSK.Models.SuKien", b =>
                {
                    b.Property<string>("MaSK")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaDiem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("End_time")
                        .HasColumnType("time");

                    b.Property<string>("MaLoaiSK")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MotaSK")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<int>("SoNgayNhac")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("Start_time")
                        .HasColumnType("time");

                    b.Property<string>("TenSK")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("end_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("max_participants")
                        .HasColumnType("int");

                    b.Property<string>("qr_code_token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("start_date")
                        .HasColumnType("datetime2");

                    b.HasKey("MaSK");

                    b.HasIndex("MaLoaiSK");

                    b.ToTable("SuKien");
                });

            modelBuilder.Entity("DA09_QLSK.Models.Notification", b =>
                {
                    b.HasOne("DA09_QLSK.Models.SuKien", "SuKien")
                        .WithMany()
                        .HasForeignKey("MaSK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DA09_QLSK.Models.PhanCong", b =>
                {
                    b.HasOne("DA09_QLSK.Models.SinhVien", "SinhVien")
                        .WithMany()
                        .HasForeignKey("Account_id");
                });

            modelBuilder.Entity("DA09_QLSK.Models.SuKien", b =>
                {
                    b.HasOne("DA09_QLSK.Models.PhanLoaiSK", "PhanLoaiSK")
                        .WithMany()
                        .HasForeignKey("MaLoaiSK");
                });
#pragma warning restore 612, 618
        }
    }
}
